import*as THREE from"https://cdn.jsdelivr.net/npm/three@0.160.0/build/three.module.js";import{OrbitControls}from"https://cdn.jsdelivr.net/npm/three@0.160.0/examples/jsm/controls/OrbitControls.js";
const $=x=>document.querySelector(x);$("#play").onclick=()=>{$("#home").style.display="none";$("#game").style.display="block";init()};$("#how").onclick=()=>$("#modal").classList.add("show");$("#close").onclick=()=>$("#modal").classList.remove("show");$("#ok").onclick=()=>{$("#modal").classList.remove("show");$("#home").style.display="none";$("#game").style.display="block";init()};
let S,C,R,O,started=false;
function init(){if(started)return;started=true;const h=$("#scene");S=new THREE.Scene();S.fog=new THREE.Fog(0x081018,14,50);C=new THREE.PerspectiveCamera(55,h.clientWidth/h.clientHeight,.1,100);C.position.set(10,8,13);R=new THREE.WebGLRenderer({antialias:true});R.setSize(h.clientWidth,h.clientHeight);R.setPixelRatio(Math.min(devicePixelRatio,2));R.shadowMap.enabled=true;h.appendChild(R.domElement);O=new OrbitControls(C,R.domElement);O.target.set(0,0,0);O.enableDamping=true;S.add(new THREE.HemisphereLight(0xb9c8ff,0x16220f,2));let L=new THREE.DirectionalLight(0xffe5b5,2.5);L.position.set(8,14,5);L.castShadow=true;S.add(L);let g=new THREE.Mesh(new THREE.PlaneGeometry(40,40),new THREE.MeshStandardMaterial({color:0x17231b,roughness:1}));g.rotation.x=-Math.PI/2;g.receiveShadow=true;S.add(g);let lake=new THREE.Mesh(new THREE.CircleGeometry(6,64),new THREE.MeshStandardMaterial({color:0x174b68,metalness:.2,roughness:.25}));lake.rotation.x=-Math.PI/2;lake.position.y=.03;S.add(lake);for(let i=0;i<26;i++)crystal();for(let i=0;i<10;i++)tree();character(-4,0xff7048,"TU");character(4,0x9b6cff,"RIVAL");throne(-7,-4,0xf1c568);throne(7,-4,0x9b6cff);newRune();addEventListener("resize",()=>{C.aspect=h.clientWidth/h.clientHeight;C.updateProjectionMatrix();R.setSize(h.clientWidth,h.clientHeight)});R.setAnimationLoop(t=>{O.update();R.render(S,C)})}
function character(x,col){let G=new THREE.Group(),m=new THREE.MeshStandardMaterial({color:col,roughness:.4});let b=new THREE.Mesh(new THREE.CylinderGeometry(.55,.7,1.4,8),m);b.position.y=.8;let hd=new THREE.Mesh(new THREE.IcosahedronGeometry(.5,1),m);hd.position.y=1.75;let cap=new THREE.Mesh(new THREE.ConeGeometry(.8,1.5,5),new THREE.MeshStandardMaterial({color:0x17172a}));cap.position.set(0,.9,-.3);G.add(b,hd,cap);G.position.set(x,0,0);G.traverse(o=>{if(o.isMesh)o.castShadow=true});S.add(G)}
function throne(x,z,col){let G=new THREE.Group(),m=new THREE.MeshStandardMaterial({color:col,metalness:.55,roughness:.35});let a=new THREE.Mesh(new THREE.BoxGeometry(1.7,.5,1.2),m);a.position.y=.6;let b=new THREE.Mesh(new THREE.BoxGeometry(1.5,2,.3),m);b.position.set(0,1.5,.4);let c=new THREE.Mesh(new THREE.ConeGeometry(.6,.7,5),m);c.position.y=2.6;G.add(a,b,c);G.position.set(x,0,z);S.add(G)}
function crystal(){let a=Math.random()*6.28,r=7+Math.random()*11,m=new THREE.Mesh(new THREE.OctahedronGeometry(.45),new THREE.MeshStandardMaterial({color:[0x62a1ff,0x9a6cff,0x55c889,0xf1a45e][Math.floor(Math.random()*4)],emissive:0x111111}));m.position.set(Math.cos(a)*r,.6,Math.sin(a)*r);m.scale.y=.6+Math.random()*2;m.castShadow=true;S.add(m)}
function tree(){let a=Math.random()*6.28,r=6+Math.random()*11,G=new THREE.Group();let t=new THREE.Mesh(new THREE.CylinderGeometry(.18,.28,1.4,6),new THREE.MeshStandardMaterial({color:0x49362b}));t.position.y=.7;let l=new THREE.Mesh(new THREE.ConeGeometry(1.1,2.8,7),new THREE.MeshStandardMaterial({color:0x17422b}));l.position.y=2.1;G.add(t,l);G.position.set(Math.cos(a)*r,0,Math.sin(a)*r);S.add(G)}
function newRune(){let r=new THREE.Mesh(new THREE.TorusGeometry(2.5,.04,8,64),new THREE.MeshBasicMaterial({color:0xf2c66a,transparent:true,opacity:.5}));r.rotation.x=Math.PI/2;r.position.y=.05;S.add(r)}
document.querySelectorAll(".actions button").forEach(b=>b.onclick=()=>{let e=+$("#energy").textContent;if(e<1)return;$("#energy").textContent=e-1;if(b.dataset.e==="water")$("#hp").textContent=Math.min(100,+$("#hp").textContent+8);if(b.dataset.e==="fire")$("#hp").textContent=Math.max(0,+$("#hp").textContent-4)});$("#end").onclick=()=>{$("#energy").textContent=6;$("#round").textContent=+$("#round").textContent+1};
const socket=io(),msgs=$("#msgs");function add(t,sys=false){let d=document.createElement("div");d.className="msg"+(sys?" system":"");d.textContent=t;msgs.appendChild(d);msgs.scrollTop=msgs.scrollHeight}socket.on("system",t=>add(t,true));socket.on("chat",t=>add(t));$("#form").onsubmit=e=>{e.preventDefault();let i=$("#input");if(i.value.trim())socket.emit("chat",i.value);i.value=""}
